# Generated by Django 3.1 on 2020-11-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_data',
            name='edited_shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history_data',
            name='final_shipping_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
