# Generated by Django 3.1 on 2020-11-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manage', '0002_subcontent_user_edit_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_data',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
